// movies
export const TOGGLE_LOADING = 'TOGGLE_LOADING';
export const UPDATE_MOVIES = 'UPDATE_MOVIES';

// auth
export const SWITCH_AUTH_MODE = 'SWITCH_AUTH_MODE';
export const TOGGLE_SUBMITTING = 'TOGGLE_SUBMITTING';
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const REMOVE_USER_MOVIES = 'REMOVE_USER_MOVIES';
export const SET_USER_MOVIES = 'SET_USER_MOVIES';

// fullMovie
export const GET_MOVIE_DATA = 'GET_MOVIE_DATA';
export const GET_CREDITS_DATA = 'GET_CREDITS_DATA';
export const UNSET_MOVIE_DATA = 'UNSET_MOVIE_DATA';
export const GET_RECOMMENDATIONS_DATA = 'GET_RECOMMENDATIONS_DATA';
